apiVersion: v1
kind: Service
metadata:
  name: three-tier-flask-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: three-tier
    tier: flask


---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: three-tier
    tier: mysql